from NHentai.core.interfaces import Sort, Doujin, SearchResult, PopularPage, CommentPage, Page

class NhentaiInterface:
    async def get_doujin(self, doujin_id: int) -> Doujin: ...
    async def get_random(self) -> Doujin: ...
    async def get_popular_now(self) -> PopularPage: ...
    async def get_comments(self, doujin_id: int) -> CommentPage: ...
    async def search_doujin(self, search_term: str, page: int=1, sort: Sort = Sort.RECENT, parallel_jobs: int=1) -> SearchResult: ...
    async def get_page(self, page: int) -> Page: ...