from typing import Any

from .interfaces import Sort, Doujin, SearchResult, PopularPage, CommentPage

class NhentaiInterface:
    async def get_doujin(self, doujin_id: int) -> Doujin: ...
    async def get_random(self) -> Doujin: ...
    async def get_characters(self, page: int) -> Any: ...
    async def get_popular_now(self) -> PopularPage: ...
    async def get_comments(self, doujin_id: int) -> CommentPage: ...
    async def search_doujin(self, search_term: str, page: int=1, sort: Sort = Sort.RECENT) -> SearchResult: ...