[build-system]
requires = ["setuptools>=64", "wheel", "setuptools_scm"]
build-backend = "setuptools.build_meta"

[project]
name = "enma"
dynamic = ["version"]

[tool.setuptools_scm]
version_file = "enma/_version.py"