from typing import Any

from NHentai.core.interfaces import Sort, Doujin, SearchResult, CommentPage, PopularPage

class NhentaiInterface:
    def get_doujin(self, doujin_id: int) -> Doujin: ...
    def get_random(self) -> Doujin: ...
    def get_characters(self, page: int) -> Any: ...
    def get_popular_now(self) -> PopularPage: ...
    def get_comments(self, doujin_id: int) -> CommentPage: ...
    def search_doujin(self, search_term: str, page: int=1, sort: Sort = Sort.RECENT) -> SearchResult: ...